### ISSUE TITLE
Create Database Models

### ISSUE THREAD

**Issue by LawlietBlack** [LawlietBlack/daily-quests#1]
WIP:
_Quest_
  name
  frequency
  description
  last completion
  icon?
  (calculated: streak, total)

_Completion_
  date

**Comment by Brigette-Eckert** [comment]
I want to set up some models.

**Comment by LawlietBlack** [comment]
_Goal_
  related to quests
  frequency

**Comment by LawlietBlack** [comment]
Challenges: Standardized, Public Goals
